set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN A14 [get_ports {col[3]}]
set_property PACKAGE_PIN A16 [get_ports {col[2]}]
set_property PACKAGE_PIN B15 [get_ports {col[1]}]
set_property PACKAGE_PIN B16 [get_ports {col[0]}]
set_property PACKAGE_PIN A15 [get_ports {row[3]}]
set_property PACKAGE_PIN A17 [get_ports {row[2]}]
set_property PACKAGE_PIN C15 [get_ports {row[1]}]
set_property PACKAGE_PIN C16 [get_ports {row[0]}]
set_property PACKAGE_PIN U7 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN V5 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN U5 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN U8 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN W6 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN W7 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN U2 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN U4 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]




set_property PACKAGE_PIN W4 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN V4 [get_ports {seg_sel[1]}]
